### ISSUE TITLE
Cannot read propert 'size' of undefined

### ISSUE THREAD

**Issue by gjbunyea** [wyattades/java-to-javascript#1]
I'm converting some simple java classes (used for some math software) and have success on many files, but consistently get the same error on others:

```

/usr/lib/node_modules/java-to-javascript/lib/index.js:144
        return `new Array(${expr.asdds.size})` // TODO multiple dimensions?
                                       ^

TypeError: Cannot read property 'size' of undefined
    at parseExpr (/usr/lib/node_modules/java-to-javascript/lib/index.js:144:40)
    at parseFieldVars (/usr/lib/node_modules/java-to-javascript/lib/index.js:162:18)
    at parseStatement (/usr/lib/node_modules/java-to-javascript/lib/index.js:177:16)
    at parseBlock (/usr/lib/node_modules/java-to-javascript/lib/index.js:234:19)
    at parseMethod (/usr/lib/node_modules/java-to-javascript/lib/index.js:259:18)
    at parseClass (/usr/lib/node_modules/java-to-javascript/lib/index.js:279:71)
    at javaAST.types.map (/usr/lib/node_modules/java-to-javascript/lib/index.js:406:61)
    at Array.map (<anonymous>)
    at javaToJavascript (/usr/lib/node_modules/java-to-javascript/lib/index.js:406:30)
    at Object.<anonymous> (/usr/lib/node_modules/java-to-javascript/cli.js:39:22)
```

Below is one such file:

``` java
public class doneButtonMatches {

	private static final int DEFAULT_IF_NOT_NUMERIC = -1; // whatever int you want when arg is bad
	private static final int FIRST_FRAC = 1; // selection code for either input for the first fraction
	private static final int SECOND_FRAC = 2; // selection code for either input for the second fraction
	private static final int ANSWER_FRAC = 3; // selection code for either input for the answer fraction

	public static boolean doneButtonMatches(Object gn1, Object gd1, Object gn2, Object gd2, Object num1, Object den1, Object num2, Object den2, Object ansNum, Object ansDen){
		int numer1, denom1, numer2, denom2, ansNumer, ansDenom, gnumer1, gdenom1, gnumer2, gdenom2;
		int inputsAsInts[] = new int[10];
		Object inputs[] = {num1, den1, num2, den2, ansNum, ansDen, gn1, gd1, gn2, gd2};
		isIntInRange f = new isIntInRange();
		for (int i = 0; i < inputs.length; i++){
			inputsAsInts[i] = f.getInt(inputs[i]); 
		}
		
		numer1 = inputsAsInts[0];
		denom1 = inputsAsInts[1];
		numer2 = inputsAsInts[2];
		denom2 = inputsAsInts[3];
		ansNumer = inputsAsInts[4];
		ansDenom = inputsAsInts[5];
		gnumer1 = inputsAsInts[6];
		gdenom1 = inputsAsInts[7];
		gnumer2 = inputsAsInts[8];
		gdenom2 = inputsAsInts[9];
		
		bugMsgNotDone b = new bugMsgNotDone();
		String hint = b.bugMsgNotDone(1, gnumer1, gdenom1, gnumer2, gdenom2, numer1, denom1, numer2, denom2, ansNumer, ansDenom);
		if(hint.equals("Looks good.  Press the Done button."))
			return true;
		return false;	
	}
}
```

My suspicion is that is has to do with that very long `String hint = b.bugMsg......` line31. But since the output is hitting an error in the `java-to-javascript` run file, I can't tell what in myfile is the issue. 

Please let me know if there's something I can do to circumvent this problem. Thanks!

**Comment by gjbunyea** [comment]
Oh I see the issue - It looks like its failing on java array declarations (which are unnecessary in JS). Looks like commenting out in the java code can solve the problem.
